import { htmlSafe } from '@ember/template';
import {
  createElement,
  Shrink,
  Waves,
  Archive,
  Earth,
  VectorSquare,
  Split,
  PenTool,
  Crosshair,
  Diamond,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Move,
  SkipBack,
  SkipForward,
  MousePointer2,
  PanelLeft,
  PanelBottom,
  ChevronRight,
  SquareStop,
  Spline,
  House,
  Search,
  Sun,
  Moon,
  Star,
  PaintBucket,
  FileArchive,
  QrCode,
  Pointer,
  Eye,
  EyeOff,
  Upload,
  Plus,
  Trash2,
  X,
  Download,
  Copy,
  Check,
  CircleCheckBig,
  CircleAlert,
  Info,
  ImagePlus,
  Menu,
  Share2,
  Users,
  RadioTower,
  File,
  Unplug,
  NotebookPen,
  Notebook,
  Folder,
  FolderPlus,
  FileText,
  FilePlus,
  Bold,
  Italic,
  List,
  ListOrdered,
  Quote,
  Code,
  Code2,
  Minus,
  Palette,
  Sticker,
  Brush,
  Eraser,
  Smile,
  SquarePen,
  ArrowLeft,
  ChevronsLeft,
  ChevronsRight,
  Type,
  PenLine,
  StickyNote,
  Calculator,
  Trophy,
  Cake,
  CalendarClock,
  Variable,
  ChartSpline,
  Delete,
  ZoomIn,
  ZoomOut,
  LocateFixed,
  History,
  RotateCcw,
  Settings,
  Monitor,
  Database,
  Ruler,
  Wallet,
  KeyRound,
  RefreshCw,
  FileSymlink,
  Image,
  Music,
  Video,
  Hash,
  CaseSensitive,
  Fingerprint,
  Braces,
  Link2,
  WholeWord,
  Diff,
  ListFilter,
  Binary,
  ShieldCheck,
  Regex,
  Clock,
  Percent,
  Proportions,
  Contrast,
  FileStack,
  Scaling,
  Timer,
  Dices,
  ArrowRightLeft,
  Package,
  Pipette,
  AppWindow,
  MonitorSmartphone,
  FileCode,
  Crop,
  Grid3x3,
  ChessKing,
  ChessQueen,
  ChessRook,
  ChessBishop,
  ChessKnight,
  ChessPawn,
  Worm,
  Bomb,
  PartyPopper,
  Zap,
  Shovel,
  TreePalm,
  Layers,
  Bot,
  Flag,
  Flame,
  Leaf,
  Scale,
  BowArrow,
  Droplets,
  Fish,
  Hammer,
  RotateCw,
  Crown,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  Pause,
  Play,
  Undo2,
  Swords,
  UserRound,
  Maximize,
  Minimize,
  SlidersHorizontal,
  Shuffle,
  Shirt,
  UserPlus,
  LogOut,
  Link,
  Sparkles,
  Handshake,
  Repeat,
  MessageCircle,
  Send,
  PictureInPicture2,
  Smartphone,
  Lock,
  Wifi,
  Volume2,
  VolumeX,
  PersonStanding,
  Camera,
  TriangleAlert,
  Save,
  Hand,
  BellRing,
  SlidersVertical,
  AudioLines,
  Gamepad2,
  Keyboard,
  Terminal,
  Bug,
  Printer,
  Scissors,
  Stamp,
  LayoutGrid,
  Film,
  Key,
  Droplet,
  CircleDot,
  SquareScissors,
  Square,
  Shield,
  Wand,
  Languages,
  Captions,
  SpellCheck,
  BookOpen,
  Aperture,
  ScanFace,
  Circle,
  MonitorPlay,
  Barcode,
  Shapes,
  Coins,
  Gauge,
  Radio,
  Globe,
  Highlighter,
  LayoutTemplate,
  Blend,
  Frame,
  Antenna,
  FolderGit2,
  LoaderPinwheel,
  MapPin,
  Network,
  Phone,
  PhoneOff,
  Mic,
  MicOff,
  VideoOff,
  ScreenShare,
  ScreenShareOff,
  PanelRightClose,
  PanelRightOpen,
  Gavel,
  CircleParking,
  Ticket,
  ScrollText,
  Landmark,
  Map as MapIcon,
  Paperclip,
  ChevronDown,
  Unlink,
  Compass,
  Cuboid,
  MousePointerClick,
  SwatchBook,
  Mountain,
  Navigation,
  CircleStop,
  Box,
  LockOpen,
  CalendarDays,
  MailOpen,
  Footprints,
  AlarmClock,
  Watch,
  ScanQrCode,
  Webcam,
  Speech,
  FileLock2,
  Orbit,
  Sigma,
  AtSign,
  UserSearch,
  ShieldAlert,
  ScanEye,
  MailSearch,
  Radar,
  Binoculars,
} from 'sketchyicons';

// Only icons listed here get bundled; add imports as new names are used.
const ICONS = {
  binoculars: Binoculars,
  radar: Radar,
  'mail-search': MailSearch,
  'scan-eye': ScanEye,
  'shield-alert': ShieldAlert,
  'user-search': UserSearch,
  shrink: Shrink,
  waves: Waves,
  archive: Archive,
  earth: Earth,
  'vector-square': VectorSquare,
  split: Split,
  'panel-right-close': PanelRightClose,
  'panel-right-open': PanelRightOpen,
  gavel: Gavel,
  'circle-parking': CircleParking,
  ticket: Ticket,
  'scroll-text': ScrollText,
  landmark: Landmark,
  map: MapIcon,
  aperture: Aperture,
  'scan-face': ScanFace,
  circle: Circle,
  'monitor-play': MonitorPlay,
  barcode: Barcode,
  shapes: Shapes,
  coins: Coins,
  gauge: Gauge,
  radio: Radio,
  globe: Globe,
  highlighter: Highlighter,
  'layout-template': LayoutTemplate,
  blend: Blend,
  frame: Frame,
  antenna: Antenna,
  printer: Printer,
  scissors: Scissors,
  stamp: Stamp,
  'layout-grid': LayoutGrid,
  film: Film,
  key: Key,
  droplet: Droplet,
  'circle-dot': CircleDot,
  'square-scissors': SquareScissors,
  square: Square,
  shield: Shield,
  wand: Wand,
  languages: Languages,
  captions: Captions,
  'spell-check': SpellCheck,
  'book-open': BookOpen,
  house: House,
  search: Search,
  sun: Sun,
  moon: Moon,
  star: Star,
  'paint-bucket': PaintBucket,
  'file-archive': FileArchive,
  'qr-code': QrCode,
  pointer: Pointer,
  eye: Eye,
  'eye-off': EyeOff,
  upload: Upload,
  plus: Plus,
  'trash-2': Trash2,
  x: X,
  download: Download,
  copy: Copy,
  check: Check,
  'circle-check-big': CircleCheckBig,
  'circle-alert': CircleAlert,
  info: Info,
  'image-plus': ImagePlus,
  menu: Menu,
  'share-2': Share2,
  users: Users,
  'radio-tower': RadioTower,
  file: File,
  unplug: Unplug,
  'notebook-pen': NotebookPen,
  notebook: Notebook,
  folder: Folder,
  'folder-plus': FolderPlus,
  'file-text': FileText,
  'file-plus': FilePlus,
  bold: Bold,
  italic: Italic,
  list: List,
  'list-ordered': ListOrdered,
  quote: Quote,
  code: Code,
  'code-2': Code2,
  minus: Minus,
  palette: Palette,
  sticker: Sticker,
  brush: Brush,
  eraser: Eraser,
  smile: Smile,
  'square-pen': SquarePen,
  'arrow-left': ArrowLeft,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  type: Type,
  'pen-line': PenLine,
  'sticky-note': StickyNote,
  calculator: Calculator,
  trophy: Trophy,
  cake: Cake,
  'calendar-clock': CalendarClock,
  variable: Variable,
  'chart-spline': ChartSpline,
  delete: Delete,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'locate-fixed': LocateFixed,
  history: History,
  'rotate-ccw': RotateCcw,
  settings: Settings,
  monitor: Monitor,
  database: Database,
  ruler: Ruler,
  wallet: Wallet,
  'key-round': KeyRound,
  'refresh-cw': RefreshCw,
  'file-symlink': FileSymlink,
  image: Image,
  music: Music,
  video: Video,
  hash: Hash,
  'case-sensitive': CaseSensitive,
  fingerprint: Fingerprint,
  braces: Braces,
  'link-2': Link2,
  'whole-word': WholeWord,
  diff: Diff,
  'list-filter': ListFilter,
  binary: Binary,
  'shield-check': ShieldCheck,
  regex: Regex,
  clock: Clock,
  percent: Percent,
  proportions: Proportions,
  contrast: Contrast,
  'file-stack': FileStack,
  scaling: Scaling,
  timer: Timer,
  dices: Dices,
  'loader-pinwheel': LoaderPinwheel,
  'arrow-right-left': ArrowRightLeft,
  package: Package,
  pipette: Pipette,
  'app-window': AppWindow,
  'monitor-smartphone': MonitorSmartphone,
  'file-code': FileCode,
  crop: Crop,
  'grid-3x3': Grid3x3,
  'chess-king': ChessKing,
  'chess-queen': ChessQueen,
  'chess-rook': ChessRook,
  'chess-bishop': ChessBishop,
  'chess-knight': ChessKnight,
  'chess-pawn': ChessPawn,
  worm: Worm,
  bomb: Bomb,
  'party-popper': PartyPopper,
  zap: Zap,
  shovel: Shovel,
  'tree-palm': TreePalm,
  layers: Layers,
  bot: Bot,
  flag: Flag,
  flame: Flame,
  leaf: Leaf,
  scale: Scale,
  'bow-arrow': BowArrow,
  droplets: Droplets,
  fish: Fish,
  hammer: Hammer,
  'rotate-cw': RotateCw,
  crown: Crown,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  pause: Pause,
  play: Play,
  'undo-2': Undo2,
  swords: Swords,
  'user-round': UserRound,
  maximize: Maximize,
  minimize: Minimize,
  'sliders-horizontal': SlidersHorizontal,
  shuffle: Shuffle,
  shirt: Shirt,
  'user-plus': UserPlus,
  'log-out': LogOut,
  link: Link,
  sparkles: Sparkles,
  handshake: Handshake,
  repeat: Repeat,
  'message-circle': MessageCircle,
  send: Send,
  'picture-in-picture': PictureInPicture2,
  smartphone: Smartphone,
  lock: Lock,
  wifi: Wifi,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'person-standing': PersonStanding,
  camera: Camera,
  'triangle-alert': TriangleAlert,
  save: Save,
  hand: Hand,
  'bell-ring': BellRing,
  'sliders-vertical': SlidersVertical,
  'audio-lines': AudioLines,
  'gamepad-2': Gamepad2,
  keyboard: Keyboard,
  terminal: Terminal,
  bug: Bug,
  'folder-git-2': FolderGit2,
  'map-pin': MapPin,
  network: Network,
  phone: Phone,
  'phone-off': PhoneOff,
  mic: Mic,
  'mic-off': MicOff,
  'video-off': VideoOff,
  'screen-share': ScreenShare,
  'screen-share-off': ScreenShareOff,
  paperclip: Paperclip,
  'chevron-down': ChevronDown,
  unlink: Unlink,
  compass: Compass,
  cuboid: Cuboid,
  'mouse-pointer-click': MousePointerClick,
  'swatch-book': SwatchBook,
  mountain: Mountain,
  navigation: Navigation,
  'circle-stop': CircleStop,
  box: Box,
  'lock-open': LockOpen,
  'calendar-days': CalendarDays,
  'mail-open': MailOpen,
  footprints: Footprints,
  'alarm-clock': AlarmClock,
  watch: Watch,
  'scan-qr-code': ScanQrCode,
  webcam: Webcam,
  speech: Speech,
  'file-lock-2': FileLock2,
  orbit: Orbit,
  sigma: Sigma,
  'at-sign': AtSign,
  'pen-tool': PenTool,
  crosshair: Crosshair,
  diamond: Diamond,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  move: Move,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'mouse-pointer-2': MousePointer2,
  'panel-left': PanelLeft,
  'panel-bottom': PanelBottom,
  'chevron-right': ChevronRight,
  'square-stop': SquareStop,
  spline: Spline,
};

function svg(name, size = 16, fill = 'none') {
  const node = ICONS[name];
  if (!node)
    throw new Error(`Unknown icon "${name}", import it in components/icon.gjs`);
  return htmlSafe(
    createElement(node, { width: size, height: size, fill }).outerHTML,
  );
}

<template>
  <span class="icon" ...attributes>{{svg @name @size @fill}}</span>
</template>
