// Names for computer players in every game: robot, AI and tech puns, one word
// each so they fit a lobby seat, a scoreboard chip and a chat line without
// wrapping or being cut off.
// Picked from a seed the host keeps in the room's settings, so everyone in a
// lobby sees the same names, and no two bots at one table share a name.

export const BOT_NAMES = [
  'Tincan',
  'HAL',
  'WALL-E',
  'Bender',
  'GLaDOS',
  'TARS',
  'EVE',
  'CASE',
  'Marvin',
  'Robby',
  'Bishop',
  'Ash',
  'Sonny',
  'Wheatley',
  'Claptrap',
  'Cortana',
  'Jarvis',
  'KITT',
  'Baymax',
  'R2D2',
  'C3PO',
  'BB8',
  'K2SO',
  'HK47',
  'IG88',
  'GERTY',
  'VIKI',
  'Ultron',
  'Optimus',
  'Bumblebot',
  'Megatron',
  'Starscream',
  'Johnny5',
  'Twiki',
  'Kryten',
  'Robotnik',
  'Rosie',
  'Astro',
  'Gort',
  'Talos',
  'Chappie',
  'M3GAN',
  'Pris',
  'Zhora',
  'Rachel',
  'K-9',
  'MetalSonic',
  'RoboCop',
  'ED209',
  'T800',
  'T1000',
  'T-X',
  'Codsworth',
  'Curie',
  'Peabody',
  'Atlas',
  'PBody',
  'MrHandy',
  'YesMan',
  'Ratchet',
  'Wattson',
  'Gearald',
  'Rustopher',
  'Solderman',
  'Bolton',
  'Ohmlet',
  'Ampere',
  'Torque',
  'Clankton',
  'Botrick',
  'Botilda',
  'Wrenchley',
  'Sprocket',
  'Byteon',
  'Gearson',
  'Voltney',
  'Wattley',
  'Rusty',
  'Sparky',
  'Fusco',
  'Ohmari',
  'Voltana',
  'Geartrude',
  'Botilda',
  'Solderine',
  'Clankie',
  'Torquella',
  'Wattilda',
  'Rustine',
  'Patch Adams',
  'Iron Giant',
  'Robo Ky',
  'Tesla',
  'Postgres Malone',
  'Betty Beep Boop',
  'Ohmagod',
  'Lagatha',
  'Sir Byte-a-Lot',
  'Chip Chatwell',
  'Bot Damon',
  'Byte Tyson',
  'Chip Skylark',
  'Cache Money',
  'Ctrlton Heston',
  'Bitney Spears',
  'Byte Midler',
  'Bot Jovi',
  'Elvis Pressley',
  'Bot Marley',
  'Byte Ruffalo',
  'Chip Hanks',
  'Cache Hudson',
  'Watt Smith',
  'Bit Reynolds',
  'Bot Diesel',
  'Watt Damon',
  'Chip Hazard',
  'Byte Solo',
  'Chip Skywalker',
  'Bot Kenobi',
  'Droid Pitt',
  'Sir RAM-a-Lot',
  'Byte Knight',
  "Chip O'Dale",
  'Bot Weasley',
  'Cache Me Outside',
  'Wattson Holmes',
  'Sherlock Ohms',
  'Nikola Tesbot',
  'Albert Einbot',
  'Ada Lovelace',
  'Charles Bobbage',
  'Alan Turning',
  'Grace Hopper',
  'Mark Zuckerbot',
  'Steve Jobot',
  'Cache Money',
  'Inspector Gadget',
  'Q5U4EX7YY2E9N',
  'ImNotARobot',
  'WoogiGPT',
  'Cookie Monster',
  'LANgela',
  'ROBYN',
  'RAMona',
  'Cybria',
  'Nettie',
  'Netta',
  'Webbie',
  'Linka',
  'Linky',
  'Codette',
  'Bitricia',
  'Toaster',
  'Herbie',
  'Grok',
  'Eggman',
  'Alexa',
  'Siri',
  'Woogle',
  'Bortus',
  'Ingram',
  'Robo Maria',
  '404',
  'Daemon',
  'Doraemon',
  'Astro Boy',
  'Astro',
  'Atom',
  'Tetsujin',
  'Akira',
  'L-Gaim',
  'Alphonse',
  'Triple-T',
  'Tung Tung Tung Sahur',
  'Capuccina Ballerina',
  'Lirili Larila',
  'Bombardino Crocodillo',
  'Tralalero Tralala',
  'Skibidi Rizz',
  'Brr Brr Patapim',
  'Eric Cartbot',
  'IWILLDOMINATE',
  'Load-Bearing',
  '67676767676767',
  'RealSteel',
  'Robbie Botten',
  'doesanybodyreadthis',
  'Orphan Crusher',
  'RAM Phage',
  'Pandoras Bot',
  'I_Eat_RAM',
  'Black Sarena',
  'Potemkin',
  'Faust',
  'Bedman',
  'Jack-O',
  'Android 21',
  'Android 16',
  'Android 17',
  'Android 18',
  'Genesect',
  'Lancelot',
  'Excalibot',
  'Botemis',
  'Roomba',
  'Violet Evergarden',
  'Chii',
  'Drossel',
  'Bad Actor',
  'Clippy',
  'BonziBuddy',
  'SmarterChild',
  'A.L.I.E.',
  'Simsimi',
  'Akinator',
  'RAM Ranger',
  'An0nym0us',
  'B(r)owser',
  'Weegee',
  'Professor Sada',
  'Professor Turo',
  'LowTierBot',
  'luisgamercool23',
  'coolkidtina101',
  'Brosio Asprer',
  'Botman',
  'Noob',
  'Herobrine',
  'Morris Worm',
  'WannaCry',
  'ILOVEYOU',
  'Conficker',
  'Netsky',
  'Sasser',
  'Code Red',
  'Shamoon',
  'Emotet',
  'NotPetya',
  'Pegasus',
  'JJSploit',
  'KRNL',
  'Synapse',
  'Fluxus',
  'WeAreDevs',
  'Proxo',
  'Oxygen U',
  'Script-Ware',
  'Calamari',
  'Eclipse X',
  'Infinite Yield',
  'SirHurtz',
  'Roaring Knight',
  'Kris',
  'Jevil',
  'Mechamaru',
  'Panda',
  'Claude',
  'FREE PALESTINE',
  'FREE UKRAINE',
  'FREE TAIWAN',
  'FREE TIBET',
  'FREE HONG KONG',
  'Net-anyahu',
  'Build-a-bot',
  'B-Bot',
  'FAS-BOR7 Horus',
  'Metal Devil',
  'Valorant Player',
  'Jenny Wakeman',
  'JackSepticBot',
  'Virtual Insanity',
  'The Botfather',
  'Truman',
  'Spock',
  'Daft Punk',
  'Roboto',
  'robots.txt',
  'Soda Machine',
  'BinaryNumbersOnly',
  'Malcolm Bott',
  'Justin Biebot',
  'PARTYNEXTGAME',
  'Tyler, The Botmaker',
  'BotPantheress',
  'Hev Abot',
  'Skusta Bot',
  'beabadoobot',
  'Radiohead',
  'Bot DeMarco',
  'AI Delas-Alas',
  'Botson Tiller',
  'Playbot Carti',
  'Lil Uzi Bot',
  'Botty Rich',
  'Botty B',
  'Botty Wap',
  'Bot Faiyaz',
  'MAC Ayres',
];

// A small, fast PRNG (mulberry32), so a seed always gives the same sequence.
export function seededRandom(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export const newBotSeed = () => Math.floor(Math.random() * 0xffffffff);

// `count` different names, the same ones for the same seed.
export function botNames(seed, count) {
  const random = seededRandom(Number(seed) || 1);
  const pool = [...BOT_NAMES];
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return Array.from({ length: count }, (_, i) => pool[i % pool.length]);
}
